chore: Add bug repro
```
[I] ccchapman@Chriss-Mac-mini ~/S/vite-ct-repro> npx vite build
vite v4.4.1 building for production...
✓ 3 modules transformed.
✓ built in 180ms
[vite:css] [postcss] postcss-import: /Users/ccchapman/Sites/vite-ct-repro/styles/typography.css:1:1: `@layer base` is used but no matching `@tailwind base` directive is p
resent.
file: /Users/ccchapman/Sites/vite-ct-repro/styles/global.css:1:1
error during build:
CssSyntaxError: [postcss] postcss-import: /Users/ccchapman/Sites/vite-ct-repro/styles/typography.css:1:1: `@layer base` is used but no matching `@tailwind base` directive
 is present.
    at Input.error (/Users/ccchapman/Sites/vite-ct-repro/node_modules/postcss/lib/input.js:106:16)
    at AtRule.error (/Users/ccchapman/Sites/vite-ct-repro/node_modules/postcss/lib/node.js:115:32)
    at normalizeTailwindDirectives (/Users/ccchapman/Sites/vite-ct-repro/node_modules/tailwindcss/lib/lib/normalizeTailwindDirectives.js:72:32)
    at /Users/ccchapman/Sites/vite-ct-repro/node_modules/tailwindcss/lib/processTailwindFeatures.js:30:98
    at plugins (/Users/ccchapman/Sites/vite-ct-repro/node_modules/tailwindcss/lib/plugin.js:38:63)
    at LazyResult.runOnRoot (/Users/ccchapman/Sites/vite-ct-repro/node_modules/postcss/lib/lazy-result.js:357:16)
    at LazyResult.runAsync (/Users/ccchapman/Sites/vite-ct-repro/node_modules/postcss/lib/lazy-result.js:286:26)
    at async compileCSS (file:///Users/ccchapman/Sites/vite-ct-repro/node_modules/vite/dist/node/chunks/dep-439026c8.js:38783:25)
    at async Object.load (file:///Users/ccchapman/Sites/vite-ct-repro/node_modules/vite/dist/node/chunks/dep-439026c8.js:38735:32)
    at async Promise.all (index 0)
```